import { describe, it, expect } from "vitest";
import { escapeHtml, buildCvHtml, type CvPdfData } from "./cv-helpers";

// ---------------------------------------------------------------------------
// Tests: buildCvHtml
// ---------------------------------------------------------------------------

describe("buildCvHtml", () => {
  const baseData: CvPdfData = {
    candidateName: "Ahmed Al-Mutawa",
    candidateEmail: "ahmed@example.com",
    candidatePhone: "+965 5555 1234",
    objective: "Experienced civil engineer seeking challenging opportunities.",
    intro: "A dedicated professional with 10+ years in construction management.",
    nationality: "Kuwaiti",
    dateOfBirth: "1990-05-15",
    civilId: "123456789012",
    education: [
      {
        university: "Kuwait University",
        degree: "Bachelor of Science",
        major: "Civil Engineering",
        graduationYear: 2012,
      },
    ],
    experience: [
      {
        role: "Senior Civil Engineer",
        employer: "ABC Construction Co.",
        startYear: 2015,
        endYear: 2024,
      },
      {
        role: "Junior Engineer",
        employer: "DEF Engineering",
        startYear: 2012,
        endYear: null,
      },
    ],
    certificates: [
      {
        title: "Project Management Professional (PMP)",
        issuer: "PMI",
      },
    ],
    skills: [
      { skill: "AutoCAD" },
      { skill: "Project Management" },
      { skill: "Structural Analysis" },
    ],
    languages: [
      { language: "Arabic", proficiency: "Native" },
      { language: "English", proficiency: "Fluent" },
    ],
    links: [
      { title: "LinkedIn", url: "https://linkedin.com/in/ahmed" },
      { title: "Portfolio", url: "https://example.com/portfolio" },
    ],
  };

  it("renders the candidate name prominently", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).toContain("<h1>");
  });

  it("renders contact information", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("ahmed@example.com");
    expect(html).toContain("+965 5555 1234");
  });

  it("renders the professional summary section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Professional Summary");
    expect(html).toContain("Experienced civil engineer");
    expect(html).toContain("construction management");
  });

  it("renders personal details section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Personal Details");
    expect(html).toContain("Nationality:");
    expect(html).toContain("Kuwaiti");
    expect(html).toContain("Date of Birth:");
    expect(html).toContain("1990-05-15");
    expect(html).toContain("Civil ID:");
  });

  it("renders experience section with roles and employers", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Experience");
    expect(html).toContain("Senior Civil Engineer");
    expect(html).toContain("ABC Construction Co.");
    expect(html).toContain("2015");
    expect(html).toContain("2024");
    expect(html).toContain("Junior Engineer");
    expect(html).toContain("DEF Engineering");
  });

  it("renders Present for ongoing experience", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Present");
  });

  it("renders education section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Education");
    expect(html).toContain("Kuwait University");
    expect(html).toContain("Bachelor of Science");
    expect(html).toContain("Civil Engineering");
    expect(html).toContain("2012");
  });

  it("renders skills section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Skills");
    expect(html).toContain("AutoCAD");
    expect(html).toContain("Project Management");
    expect(html).toContain("Structural Analysis");
  });

  it("renders languages section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Languages");
    expect(html).toContain("Arabic");
    expect(html).toContain("Native");
    expect(html).toContain("English");
    expect(html).toContain("Fluent");
  });

  it("renders certificates section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Certificates");
    expect(html).toContain("Project Management Professional (PMP)");
    expect(html).toContain("PMI");
  });

  it("renders links section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Links");
    expect(html).toContain("LinkedIn");
    expect(html).toContain("linkedin.com/in/ahmed");
    expect(html).toContain("Portfolio");
  });

  it("renders the Generated by StudentHub footer", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Generated by StudentHub");
    expect(html).toContain("Candidate CV");
  });

  it("escapes HTML in candidate name", () => {
    const data: CvPdfData = {
      ...baseData,
      candidateName: "<script>alert('xss')</script>",
    };
    const html = buildCvHtml(data);
    expect(html).toContain("&lt;script&gt;alert(&#039;xss&#039;)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert('xss')</script>");
  });

  it("handles minimal data gracefully", () => {
    const minimal: CvPdfData = {
      candidateName: "Test User",
      candidateEmail: "",
      candidatePhone: null,
      objective: null,
      intro: null,
      nationality: null,
      dateOfBirth: null,
      civilId: null,
      education: [],
      experience: [],
      certificates: [],
      skills: [],
      languages: [],
      links: [],
    };
    const html = buildCvHtml(minimal);
    expect(html).toContain("Test User");
    expect(html).not.toContain("undefined");
    expect(html).not.toContain("null");
    expect(html).not.toContain("Professional Summary");
    expect(html).not.toContain("Personal Details");
    expect(html).not.toContain("Experience");
    expect(html).not.toContain("Education");
    expect(html).not.toContain("Skills");
    expect(html).not.toContain("Languages");
    expect(html).not.toContain("Certificates");
    expect(html).not.toContain("Links");
  });

  it("escapes HTML in all user-provided fields", () => {
    const data: CvPdfData = {
      ...baseData,
      objective: "<script>alert('obj')</script>",
      education: [{ university: "<b>Univ</b>", degree: "<i>Degree</i>", major: null, graduationYear: null }],
      experience: [{ role: "<b>Role</b>", employer: "<i>Co</i>", startYear: null, endYear: null }],
      skills: [{ skill: "<script>skill</script>" }],
      languages: [{ language: "<b>Lang</b>", proficiency: "<i>Native</i>" }],
    };
    const html = buildCvHtml(data);
    expect(html).not.toContain("<script>alert('obj')</script>");
    expect(html).not.toContain("<b>Univ</b>");
    expect(html).not.toContain("<b>Role</b>");
    expect(html).not.toContain("<script>skill</script>");
    expect(html).not.toContain("<b>Lang</b>");
    expect(html).toContain("&lt;b&gt;Univ&lt;/b&gt;");
  });

  it("uses print-friendly styles", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("@media print");
  });

  it("renders a header with the candidate name and contact", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).toContain("ahmed@example.com");
    expect(html).toContain("+965 5555 1234");
  });
});
