import { describe, it, expect } from "vitest";
import { escapeHtml, buildIdCardHtml, type IdCardPdfData } from "./pdf-helpers";

// ---------------------------------------------------------------------------
// Tests: escapeHtml (shared utility — consistent contract)
// ---------------------------------------------------------------------------

describe("escapeHtml", () => {
  it("escapes ampersands", () => {
    expect(escapeHtml("A & B")).toBe("A &amp; B");
  });

  it("escapes less-than signs", () => {
    expect(escapeHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("escapes double quotes", () => {
    expect(escapeHtml('He said "hello"')).toBe("He said &quot;hello&quot;");
  });

  it("handles strings with no special chars", () => {
    expect(escapeHtml("Hello World")).toBe("Hello World");
  });

  it("handles empty string", () => {
    expect(escapeHtml("")).toBe("");
  });
});

// ---------------------------------------------------------------------------
// Tests: buildIdCardHtml
// ---------------------------------------------------------------------------

describe("buildIdCardHtml", () => {
  const baseData: IdCardPdfData = {
    candidateName: "Ahmed Al-Mutawa",
    candidateId: 12345,
    idCardNumber: "IC-2026-001",
    nationality: "Kuwaiti",
    dateOfBirth: "1995-06-15",
    expiryDate: "2027-06-15",
    photoUrl: null,
    qrCodeDataUrl: null,
  };

  it("renders the candidate name prominently", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Ahmed Al-Mutawa");
  });

  it("renders the ID card number", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("IC-2026-001");
  });

  it("renders nationality", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Kuwaiti");
  });

  it("renders the expiry date", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("2027-06-15");
  });

  it("renders the candidate ID", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("12345");
  });

  it("includes a header indicating it's an ID card", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("StudentHub");
    expect(html).toContain("ID Card");
  });

  it("renders the footer with generated-by notice", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Generated by StudentHub");
  });

  it("does not render empty photo section when photoUrl is null", () => {
    const html = buildIdCardHtml(baseData);
    // No img tag with src when photo is null
    expect(html).not.toContain('<img src=""');
  });

  it("renders photo when photoUrl is provided", () => {
    const data: IdCardPdfData = {
      ...baseData,
      photoUrl: "https://example.com/photo.jpg",
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("https://example.com/photo.jpg");
  });

  it("escapes HTML in candidate name", () => {
    const data: IdCardPdfData = {
      ...baseData,
      candidateName: "<script>alert('xss')</script>",
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("&lt;script&gt;alert(&#039;xss&#039;)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert('xss')</script>");
  });

  it("handles optional fields gracefully", () => {
    const data: IdCardPdfData = {
      ...baseData,
      nationality: null,
      dateOfBirth: null,
      expiryDate: null,
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).not.toContain("undefined");
    expect(html).not.toContain("null");
  });

  it("uses print-friendly styles", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("@media print");
  });

  it("renders the ID as a card-like layout with a border", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("border");
    expect(html).toContain("ID Card");
  });
});
