import { describe, it, expect } from "vitest";
import { escapeHtml, buildOfferLetterHtml, type OfferLetterData } from "./offer-letter-pdf-helpers";

// ---------------------------------------------------------------------------
// Tests: escapeHtml (shared utility)
// ---------------------------------------------------------------------------

describe("escapeHtml", () => {
  it("escapes special characters", () => {
    expect(escapeHtml("A & B <script>")).toBe("A &amp; B &lt;script&gt;");
  });
});

// ---------------------------------------------------------------------------
// Tests: buildOfferLetterHtml
// ---------------------------------------------------------------------------

describe("buildOfferLetterHtml", () => {
  const baseData: OfferLetterData = {
    candidateName: "Ahmed Al-Mutawa",
    candidateEmail: "ahmed@example.com",
    position: "Senior Software Engineer",
    department: "Engineering",
    startDate: "2026-07-01",
    salary: "1,800 KWD/month",
    workLocation: "Salmiya Tower, Kuwait City",
    employmentType: "Full-time",
    companyName: "StudentHub",
    hrName: "Noor Al-Sabah",
    offerDate: "June 20, 2026",
    expiryDate: "July 4, 2026",
    additionalTerms:
      "Benefits include health insurance, 30 days annual leave, and professional development budget.",
  };

  it("renders the title with company name", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("<title>Offer Letter — StudentHub</title>");
  });

  it("renders the candidate name", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("Ahmed Al-Mutawa");
  });

  it("renders position and department", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("Senior Software Engineer");
    expect(html).toContain("Engineering");
  });

  it("renders salary and start date", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("1,800 KWD/month");
    expect(html).toContain("2026-07-01");
  });

  it("renders work location and employment type", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("Salmiya Tower, Kuwait City");
    expect(html).toContain("Full-time");
  });

  it("renders HR name and offer/expiry dates", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("Noor Al-Sabah");
    expect(html).toContain("June 20, 2026");
    expect(html).toContain("July 4, 2026");
  });

  it("renders additional terms", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("health insurance");
    expect(html).toContain("professional development budget");
  });

  it("escapes HTML in candidate name", () => {
    const data: OfferLetterData = {
      ...baseData,
      candidateName: "<b>Hacker</b>",
    };
    const html = buildOfferLetterHtml(data);
    expect(html).toContain("&lt;b&gt;Hacker&lt;/b&gt;");
    expect(html).not.toContain("<b>Hacker</b>");
  });

  it("handles empty additional terms gracefully", () => {
    const data: OfferLetterData = {
      ...baseData,
      additionalTerms: "",
    };
    const html = buildOfferLetterHtml(data);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).not.toContain("undefined");
    expect(html).not.toContain("null");
  });

  it("renders the footer with page numbering placeholder", () => {
    const html = buildOfferLetterHtml(baseData);
    expect(html).toContain("Offer Letter");
    expect(html).toContain("Generated by StudentHub");
  });
});
