// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/candidates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/candidates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/candidates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/candidates">> = Specific
  const handler = {} as typeof import("../../src/app/admin/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/companies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/companies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/companies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/requests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transfers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transfers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transfers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transfers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/edit">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/invitations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/invitations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/invitations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/invitations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/invitations">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/invitations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/payments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/payments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/payments">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/work-logs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/work-logs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/work-logs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/work-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/work-logs">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/work-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/companies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/companies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/company/companies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/companies">> = Specific
  const handler = {} as typeof import("../../src/app/company/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/company/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company">> = Specific
  const handler = {} as typeof import("../../src/app/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/company/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/requests/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/requests/create">> = Specific
  const handler = {} as typeof import("../../src/app/company/requests/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/requests">> = Specific
  const handler = {} as typeof import("../../src/app/company/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/stores">> = Specific
  const handler = {} as typeof import("../../src/app/company/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inspector/id-requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspector/id-requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/inspector/id-requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inspector/id-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspector/id-requests">> = Specific
  const handler = {} as typeof import("../../src/app/inspector/id-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inspector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspector">> = Specific
  const handler = {} as typeof import("../../src/app/inspector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/candidates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/candidates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/staff/candidates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/candidates">> = Specific
  const handler = {} as typeof import("../../src/app/staff/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/interviews/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/interviews/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/staff/interviews/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/interviews">> = Specific
  const handler = {} as typeof import("../../src/app/staff/interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../src/app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/staff/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/requests">> = Specific
  const handler = {} as typeof import("../../src/app/staff/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dev/impersonate">> = Specific
  const handler = {} as typeof import("../../src/app/dev/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/candidate">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/company">> = Specific
  const handler = {} as typeof import("../../src/app/company/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inspector/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inspector">> = Specific
  const handler = {} as typeof import("../../src/app/inspector/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../src/app/staff/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
