// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/candidates" | "/admin/candidates/[id]" | "/admin/companies" | "/admin/companies/[id]" | "/admin/requests" | "/admin/requests/[id]" | "/admin/transfers" | "/admin/transfers/[id]" | "/app" | "/candidate" | "/candidate/edit" | "/candidate/invitations" | "/candidate/invitations/[id]" | "/candidate/payments" | "/candidate/payments/[id]" | "/candidate/work-logs" | "/candidate/work-logs/[id]" | "/company" | "/company/companies" | "/company/companies/[id]" | "/company/contacts" | "/company/requests" | "/company/requests/[id]" | "/company/requests/create" | "/company/stores" | "/inspector" | "/inspector/id-requests" | "/inspector/id-requests/[id]" | "/login" | "/staff" | "/staff/candidates" | "/staff/candidates/[id]" | "/staff/interviews" | "/staff/interviews/[id]" | "/staff/requests" | "/staff/requests/[id]"
type AppRouteHandlerRoutes = "/dev/impersonate"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/app" | "/candidate" | "/company" | "/inspector" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/candidates": {}
  "/admin/candidates/[id]": { "id": string; }
  "/admin/companies": {}
  "/admin/companies/[id]": { "id": string; }
  "/admin/requests": {}
  "/admin/requests/[id]": { "id": string; }
  "/admin/transfers": {}
  "/admin/transfers/[id]": { "id": string; }
  "/app": {}
  "/candidate": {}
  "/candidate/edit": {}
  "/candidate/invitations": {}
  "/candidate/invitations/[id]": { "id": string; }
  "/candidate/payments": {}
  "/candidate/payments/[id]": { "id": string; }
  "/candidate/work-logs": {}
  "/candidate/work-logs/[id]": { "id": string; }
  "/company": {}
  "/company/companies": {}
  "/company/companies/[id]": { "id": string; }
  "/company/contacts": {}
  "/company/requests": {}
  "/company/requests/[id]": { "id": string; }
  "/company/requests/create": {}
  "/company/stores": {}
  "/dev/impersonate": {}
  "/inspector": {}
  "/inspector/id-requests": {}
  "/inspector/id-requests/[id]": { "id": string; }
  "/login": {}
  "/staff": {}
  "/staff/candidates": {}
  "/staff/candidates/[id]": { "id": string; }
  "/staff/interviews": {}
  "/staff/interviews/[id]": { "id": string; }
  "/staff/requests": {}
  "/staff/requests/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/app": never
  "/candidate": never
  "/company": never
  "/inspector": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
