import { describe, it, expect } from "vitest";
import { escapeHtml, buildCvHtml, type CvPdfData } from "./cv-pdf-helpers";

// ---------------------------------------------------------------------------
// Tests: escapeHtml (shared utility — same contract as evaluation version)
// ---------------------------------------------------------------------------

describe("escapeHtml", () => {
  it("escapes ampersands", () => {
    expect(escapeHtml("A & B")).toBe("A &amp; B");
  });

  it("escapes less-than signs", () => {
    expect(escapeHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("escapes double quotes", () => {
    expect(escapeHtml('He said "hello"')).toBe("He said &quot;hello&quot;");
  });

  it("handles strings with no special chars", () => {
    expect(escapeHtml("Hello World")).toBe("Hello World");
  });

  it("handles empty string", () => {
    expect(escapeHtml("")).toBe("");
  });
});

// ---------------------------------------------------------------------------
// Tests: buildCvHtml
// ---------------------------------------------------------------------------

describe("buildCvHtml", () => {
  const baseData: CvPdfData = {
    candidateName: "Ahmed Al-Mutawa",
    candidateEmail: "ahmed@example.com",
    candidatePhone: "+965 5123 4567",
    candidateObjective:
      "Experienced software engineer looking for remote opportunities.",
    candidateBirthDate: "1995-06-15",
    candidateGender: "Male",
    nationality: "Kuwaiti",
    address: "Salmiya, Kuwait City",
    educationRows: `
    <tr>
      <td>BSc Computer Science</td>
      <td>Kuwait University</td>
      <td>2017 – 2021</td>
    </tr>`,
    experienceRows: `
    <tr>
      <td>Senior Developer</td>
      <td>Tech Co</td>
      <td>2021 – Present</td>
    </tr>`,
    skillTags: "JavaScript, TypeScript, React, Node.js",
    languageRows: `
    <tr>
      <td>Arabic</td>
      <td>Native</td>
    </tr>
    <tr>
      <td>English</td>
      <td>Fluent</td>
    </tr>`,
  };

  it("renders the candidate name in the title", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("<title>CV — Ahmed Al-Mutawa</title>");
  });

  it("renders personal info section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("ahmed@example.com");
    expect(html).toContain("+965 5123 4567");
    expect(html).toContain("Kuwaiti");
    expect(html).toContain("Salmiya, Kuwait City");
  });

  it("renders the candidate objective", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Experienced software engineer");
  });

  it("renders education section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Kuwait University");
    expect(html).toContain("BSc Computer Science");
  });

  it("renders experience section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Senior Developer");
    expect(html).toContain("Tech Co");
  });

  it("renders skills section as individual tags", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("JavaScript");
    expect(html).toContain("TypeScript");
    expect(html).toContain("React");
    expect(html).toContain("Node.js");
  });

  it("renders languages section", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Arabic");
    expect(html).toContain("English");
    expect(html).toContain("Fluent");
  });

  it("escapes HTML in candidate name", () => {
    const data: CvPdfData = {
      ...baseData,
      candidateName: "<script>alert('xss')</script>",
    };
    const html = buildCvHtml(data);
    expect(html).toContain("&lt;script&gt;alert(&#039;xss&#039;)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert('xss')</script>");
  });

  it("handles empty optional fields gracefully", () => {
    const data: CvPdfData = {
      ...baseData,
      candidateObjective: "",
      candidatePhone: null,
      nationality: null,
      address: null,
      educationRows: "",
      experienceRows: "",
      skillTags: "",
      languageRows: "",
    };
    const html = buildCvHtml(data);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).toContain("ahmed@example.com");
    expect(html).not.toContain("undefined");
    expect(html).not.toContain("null");
  });

  it("renders the footer", () => {
    const html = buildCvHtml(baseData);
    expect(html).toContain("Generated by StudentHub");
  });
});
