import { describe, it, expect } from "vitest";
import { escapeHtml, buildIdCardHtml, type IdCardPdfData } from "./id-card-pdf-helpers";

// ---------------------------------------------------------------------------
// Tests: escapeHtml
// ---------------------------------------------------------------------------

describe("escapeHtml", () => {
  it("escapes ampersands", () => {
    expect(escapeHtml("A & B")).toBe("A &amp; B");
  });

  it("escapes less-than signs", () => {
    expect(escapeHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("escapes greater-than signs", () => {
    expect(escapeHtml(">test<")).toBe("&gt;test&lt;");
  });

  it("escapes double quotes", () => {
    expect(escapeHtml('He said "hello"')).toBe("He said &quot;hello&quot;");
  });

  it("escapes single quotes", () => {
    expect(escapeHtml("it's")).toBe("it&#039;s");
  });

  it("handles strings with no special chars", () => {
    expect(escapeHtml("Hello World")).toBe("Hello World");
  });

  it("handles empty string", () => {
    expect(escapeHtml("")).toBe("");
  });
});

// ---------------------------------------------------------------------------
// Tests: buildIdCardHtml
// ---------------------------------------------------------------------------

describe("buildIdCardHtml", () => {
  const baseData: IdCardPdfData = {
    candidateName: "Ahmed Al-Mutawa",
    candidateNameAr: "أحمد المطوع",
    candidateEmail: "ahmed@example.com",
    candidatePhone: "+965 5123 4567",
    candidateCivilId: "284061234567",
    candidateCivilExpiryDate: "2030-06-15",
    candidateBirthDate: "1995-06-15",
    candidateGender: "Male",
    nationality: "Kuwaiti",
    photoUrl: "https://cdn.studenthub.co/photos/ahmed.jpg",
  };

  it("renders the candidate name in the title", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("<title>Civil ID Card — Ahmed Al-Mutawa</title>");
  });

  it("renders personal details in the body", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Ahmed Al-Mutawa");
    expect(html).toContain("ahmed@example.com");
    expect(html).toContain("+965 5123 4567");
    expect(html).toContain("Kuwaiti");
    expect(html).toContain("Male");
  });

  it("renders the civil ID number prominently", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("284061234567");
  });

  it("renders the Arabic name when provided", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("أحمد المطوع");
  });

  it("renders a photo img tag when photoUrl is provided", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("<img");
    expect(html).toContain("ahmed.jpg");
  });

  it("renders a placeholder with initials when photoUrl is null", () => {
    const data: IdCardPdfData = { ...baseData, photoUrl: null };
    const html = buildIdCardHtml(data);
    expect(html).not.toContain("<img");
    expect(html).toContain("photo-placeholder");
  });

  it("shows a dash when civil ID is missing", () => {
    const data: IdCardPdfData = { ...baseData, candidateCivilId: null };
    const html = buildIdCardHtml(data);
    expect(html).toContain("—");
    expect(html).toContain("missing");
  });

  it("shows dashes for missing optional fields", () => {
    const data: IdCardPdfData = {
      candidateName: "Noor Al-Ali",
      candidateNameAr: null,
      candidateEmail: null,
      candidatePhone: null,
      candidateCivilId: null,
      candidateCivilExpiryDate: null,
      candidateBirthDate: null,
      candidateGender: null,
      nationality: null,
      photoUrl: null,
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("Noor Al-Ali");
    expect(html).not.toContain("undefined");
    expect(html).not.toContain("null");
  });

  it("renders the footer with current year", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Generated by StudentHub");
  });

  it("escapes HTML in candidate name (XSS protection)", () => {
    const data: IdCardPdfData = {
      ...baseData,
      candidateName: "<script>alert('xss')</script>",
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("&lt;script&gt;alert(&#039;xss&#039;)&lt;/script&gt;");
    expect(html).not.toContain("<script>alert('xss')</script>");
  });

  it("escapes HTML in nationality field", () => {
    const data: IdCardPdfData = {
      ...baseData,
      nationality: "<b>Kuwaiti</b>",
    };
    const html = buildIdCardHtml(data);
    expect(html).toContain("&lt;b&gt;Kuwaiti&lt;/b&gt;");
    expect(html).not.toContain("<b>Kuwaiti</b>");
  });

  it("renders Civil ID Card header", () => {
    const html = buildIdCardHtml(baseData);
    expect(html).toContain("Civil ID Card");
    expect(html).toContain("StudentHub");
  });
});
